app.js
index.html
styles.css

adding link button

---

app.js
bindings/numeric-text.js
bindings/ol-map.js
index.html
main.js
styles.css

initial work on map

---

bindings/ol-map.js

using relative protocols

---

fees/rincon-hill-infrastructure/component.js
fees/rincon-hill-infrastructure/settings.json
fees/rincon-hill-infrastructure/template.html
fees/rincon-hill-infrastructure/viewmodel.js
settings.json

66 rincon hill fee

---

fees/visitacion-valley-infrastructure/component.js
fees/visitacion-valley-infrastructure/settings.json
fees/visitacion-valley-infrastructure/template.html
fees/visitacion-valley-infrastructure/viewmodel.js
settings.json

re #72, Added initial files for Visitacion Valley fee

72 visitacion valley

---

fees/balboa-park-infrastructure/viewmodel.js
fees/market-octavia-infrastructure/component.js
fees/market-octavia-infrastructure/settings.json
fees/market-octavia-infrastructure/template.html
fees/market-octavia-infrastructure/viewmodel.js
settings.json

65 market octavia

---

app.js
bindings/ol-map.js
fees/downtown-park-fee/template.html
settings.json

updates for downtown park fee

---

fees/market-octavia-affordable-housing/component.js
fees/market-octavia-affordable-housing/info.md
fees/market-octavia-affordable-housing/settings.json
fees/market-octavia-affordable-housing/template.html
fees/market-octavia-affordable-housing/viewmodel.js
settings.json

Add market and octavia affordable housing fee.

Add market and octavia affordable housing fee re #64

---

bindings/ol-map.js
fees/market-octavia-affordable-housing/viewmodel.js
settings.json

adding layers to map, refactoring

---

bindings/ratio-text.js
fees/balboa-park-infrastructure/template.html
fees/market-octavia-affordable-housing/template.html
fees/market-octavia-infrastructure/template.html
fees/mock-fee/template.html
fees/rincon-hill-infrastructure/template.html
fees/soma-community-stabilization-fee/template.html
fees/soma-non-residential-open-space/template.html
fees/van-ness-market-infrastructure/settings.json
fees/van-ness-market-infrastructure/template.html
fees/van-ness-market-infrastructure/viewmodel.js
fees/visitacion-valley-infrastructure/template.html
main.js
settings.json

van ness market fee

---

app.js
fees/downtown-park-fee/settings.json
fees/downtown-park-fee/template.html
fees/downtown-park-fee/viewmodel.js
fees/soma-non-residential-open-space/settings.json
fees/soma-non-residential-open-space/template.html
fees/soma-non-residential-open-space/viewmodel.js
fees/transit-center-open-space/component.js
fees/transit-center-open-space/info.md
fees/transit-center-open-space/settings.json
fees/transit-center-open-space/template.html
fees/transit-center-open-space/viewmodel.js
index.html
settings.json

transit center open space

---

fees/transit-center-open-space/template.html
fees/transit-center-open-space/viewmodel.js

fixing calculation logic

---

app.js
fees/visitacion-valley-infrastructure/settings.json
fees/visitacion-valley-infrastructure/viewmodel.js
index.html

Added existing units variable to dwelling form

---

bindings/dollars-text.js
fees/citywide-childcare-residential/settings.json
fees/citywide-childcare-residential/template.html
fees/citywide-childcare-residential/viewmodel.js

fixes for childcare fee

---

index.html

updating diclaimer text

---

fees/transit-center-open-space/template.html
fees/transit-center-open-space/viewmodel.js

fixes fee calculation logic

---

fees/transit-center-transportation/template.html
fees/transit-center-transportation/viewmodel.js

Fixes to the fee proportioning calc

---

app.js
fees/abstract-fee.js
fees/eastern-neighborhoods-infrastructure/component.js
fees/eastern-neighborhoods-infrastructure/readme.md
fees/eastern-neighborhoods-infrastructure/settings.json
fees/eastern-neighborhoods-infrastructure/template.html
fees/eastern-neighborhoods-infrastructure/viewmodel.js
index.html
settings.json
styles.css
utils/mapserver.js

eastern neighborhoods infrastructure fee

---

fees/eastern-neighborhoods-infrastructure/viewmodel.js

ready logic for EN infrastructure

---

fees/eastern-neighborhoods-infrastructure/settings.json
fees/eastern-neighborhoods-infrastructure/viewmodel.js
utils/mapserver.js

eastern neighborhoods infrastructure

---

fees/eastern-neighborhoods-infrastructure/viewmodel.js

refactoring

---

styles.css

style improvements

---

fees/eastern-neighborhoods-infrastructure/settings.json
fees/eastern-neighborhoods-infrastructure/template.html
fees/eastern-neighborhoods-infrastructure/viewmodel.js

Splitting EN Change of Use fields from other Change of Use fields (defined differently in EN)

63 eastern neighborhoods infrastructure

---

fees/citywide-childcare-residential/template.html

Change from Change of Use to Change or Replacement of Use

#53 Label change

---

fees/eastern-neighborhoods-infrastructure/template.html

Added new non-residential field

#63 - Added new non-res

---

index.html

Increase in Office GFA on initial page had an ID of 'resGFA', changed this to 'officeGFA'.

#143 - UI change - error in id

---

fees/soma-non-residential-open-space/settings.json
settings.json

Alphabetical sort of the 2 fee lists (supported and unsupported), slight change to 2 fee type names (TSF and TIDF).

#143 Various UI changes

---

styles.css

Small chane to CSS to reduce height of banner.

#143 UI change

---

index.html

#143 change to 1 meta tab

---

fees/jobs-housing-linkage/template.html
fees/jobs-housing-linkage/viewmodel.js

fixes label

---

app.js
fees/eastern-neighborhoods-non-residential-open-space/component.js
fees/eastern-neighborhoods-non-residential-open-space/readme.md
fees/eastern-neighborhoods-non-residential-open-space/settings.json
fees/eastern-neighborhoods-non-residential-open-space/template.html
fees/eastern-neighborhoods-non-residential-open-space/viewmodel.js
index.html
settings.json

Add eastern neighborhoods non-residential open space fee, re #76

Add eastern neighborhoods non-residential open space fee, re #76

---

fees/eastern-neighborhoods-non-residential-open-space/template.html
fees/jobs-housing-linkage/readme.md
fees/jobs-housing-linkage/settings.json
fees/jobs-housing-linkage/template.html
fees/jobs-housing-linkage/viewmodel.js

adds change and replacement

---

fees/eastern-neighborhoods-residential-open-space/readme.md
fees/eastern-neighborhoods-residential-open-space/settings.json
fees/eastern-neighborhoods-residential-open-space/template.html
fees/eastern-neighborhoods-residential-open-space/viewmodel.js

updates fee to collect shortfall

---

fees/jobs-housing-linkage/template.html
fees/jobs-housing-linkage/viewmodel.js

calculates new as portion of total

---

bindings/ol-map.js
fees/public-art/settings.json

fixes for public art fee

---

fees/eastern-neighborhoods-non-residential-open-space/settings.json

fixes error

---

fees/affordable-housing/settings.json
fees/affordable-housing/template.html
fees/affordable-housing/viewmodel.js

adds exemption

---

fees/transportation-sustainability-fee/settings.json

fixes non-res gfa calculation

---

fees/jobs-housing-linkage/settings.json
fees/jobs-housing-linkage/viewmodel.js

fixes trigger logic

---

fees/abstract-fee.js
utils/mapserver.js

enahances mapserver for areas w/ multiple geoms

---

fees/central-soma-community-facilities/component.js
fees/central-soma-community-facilities/readme.md
fees/central-soma-community-facilities/settings.json
fees/central-soma-community-facilities/template.html
fees/central-soma-community-facilities/viewmodel.js
settings.json

Adding Central SoMa Community Facilities Fee

Adding Central SoMa Community Facilities Fee

---

fees/affordable-housing/readme.md
fees/affordable-housing/settings.json
fees/affordable-housing/template.html
fees/affordable-housing/viewmodel.js

Changes to Affordable Housing Fees #51 and #70 to match the Inclusionary Housing Fee affidavit

Changes to Affordable Housing Fees #51 and #70 to match the affidavit

---

fees/affordable-housing/template.html
fees/central-soma-infrastructure/component.js
fees/central-soma-infrastructure/readme.md
fees/central-soma-infrastructure/settings.json
fees/central-soma-infrastructure/template.html
fees/central-soma-infrastructure/viewmodel.js
settings.json

Initial work on Central SoMa Infrastructure Fee

Initial work on Central SoMa Infrastructure Fee

---

fees/affordable-housing/template.html

Slight name change and addition of link

Slight name change and addition of link

---

fees/affordable-housing/settings.json
fees/affordable-housing/template.html
fees/balboa-park-infrastructure/settings.json
fees/bicycle-parking-in-lieu/settings.json
fees/citywide-childcare-hotel-office/settings.json
fees/citywide-childcare-residential/settings.json
fees/downtown-special-development-district-open-space/settings.json
fees/eastern-neighborhoods-infrastructure/settings.json
fees/eastern-neighborhoods-non-residential-open-space/settings.json
fees/eastern-neighborhoods-residential-open-space/settings.json
fees/jobs-housing-linkage/settings.json
fees/market-octavia-affordable-housing/settings.json
fees/market-octavia-infrastructure/settings.json
fees/public-art/settings.json
fees/rincon-hill-infrastructure/settings.json
fees/soma-community-stabilization-fee/settings.json
fees/transit-center-open-space/settings.json
fees/transit-center-transportation/settings.json
fees/transportation-sustainability-fee/settings.json
fees/van-ness-market-infrastructure/settings.json
fees/visitacion-valley-infrastructure/settings.json
settings.json

Mainly changes to the fee names to match the impact fee schedule and reordering of fees.

Range of UI changes

---

settings.json

Change to title, added Union Squ to unsupported fees

Change to title, added Union Squ to unsupported fees

---

index.html
settings.json

Changes to the placeholder text, rearranging input order, adding fee list to Trigger page.

UI changes to Trigger Page

---

settings.json

Removing the contral soma fees from the unsupported list

Removing the contral soma fees from the unsupported list

---

fees/central-soma-infrastructure/settings.json

Bug fix - fee was not triggering

Bug fix - fee was not triggering

---

fees/abstract-fee.js
fees/affordable-housing/viewmodel.js
fees/balboa-park-infrastructure/viewmodel.js
fees/bicycle-parking-in-lieu/viewmodel.js
fees/central-soma-community-facilities/viewmodel.js
fees/central-soma-infrastructure/viewmodel.js
fees/citywide-childcare-hotel-office/viewmodel.js
fees/citywide-childcare-residential/viewmodel.js
fees/downtown-park-fee/viewmodel.js
fees/downtown-special-development-district-open-space/viewmodel.js
fees/eastern-neighborhoods-infrastructure/viewmodel.js
fees/eastern-neighborhoods-non-residential-open-space/viewmodel.js
fees/eastern-neighborhoods-residential-open-space/viewmodel.js
fees/jobs-housing-linkage/viewmodel.js
fees/market-octavia-affordable-housing/viewmodel.js
fees/market-octavia-infrastructure/viewmodel.js
fees/north-of-market-residential-special-use-district-affordable-housing-fee/viewmodel.js
fees/public-art/viewmodel.js
fees/rincon-hill-infrastructure/viewmodel.js
fees/soma-community-stabilization-fee/viewmodel.js
fees/transit-center-open-space/viewmodel.js
fees/transit-center-transportation/viewmodel.js
fees/transportation-sustainability-fee/viewmodel.js
fees/union-square-park-recreation-and-open-space/viewmodel.js
fees/van-ness-market-infrastructure/viewmodel.js
fees/visitacion-valley-infrastructure/viewmodel.js

Deleted isArticle25 function from each fee and placed in parent fee (Abstract-fee.js)

placed isArticle25 function in abstract-fee instead

---

.gitignore
fees/north-of-market-residential-special-use-district-affordable-housing-fee/template.html
fees/north-of-market-residential-special-use-district-affordable-housing-fee/viewmodel.js
index.html

north of market fee was updated tocalculate residential GFA instead of office GFA.

update north of market fee and add fee list back

---

settings.json

Removing 'beta' from title

---

fees/north-of-market-residential-special-use-district-affordable-housing-fee/viewmodel.js
index.html

add period in index.html

---

index.html
settings.json

removing period from index.html

removing period from index.html

---

app.js
fees/north-of-market-residential-special-use-district-affordable-housing-fee/settings.json
fees/north-of-market-residential-special-use-district-affordable-housing-fee/template.html
fees/north-of-market-residential-special-use-district-affordable-housing-fee/viewmodel.js

update fee to allow user to input residential GFA above 80 feet. also deleted old commented out cold in template.html

update north of market fee

---

fees/north-of-market-residential-special-use-district-affordable-housing-fee/viewmodel.js

previously north of market fee was blocking view report button even when all triggered fees were filled out

update trigger for view model in north of market fee

---

fees/balboa-park-infrastructure/template.html
fees/central-soma-community-facilities/template.html
fees/central-soma-infrastructure/template.html
fees/citywide-childcare-hotel-office/template.html
fees/citywide-childcare-residential/template.html
fees/eastern-neighborhoods-infrastructure/template.html
fees/jobs-housing-linkage/template.html
fees/market-octavia-affordable-housing/template.html
fees/market-octavia-infrastructure/template.html
fees/rincon-hill-infrastructure/template.html
fees/transportation-sustainability-fee/template.html
fees/visitacion-valley-infrastructure/template.html

Changes to labels, clarifying that new construction is net new construction.

Changes to labels

---

fees/balboa-park-infrastructure/readme.md
fees/citywide-childcare-residential/settings.json

Update some missing fee changes (residential child care fee, 2019 --> 2020)

Update additional changes in the impact fee rate for 2020

---

fees/jobs-housing-linkage/settings.json
fees/jobs-housing-linkage/template.html
fees/jobs-housing-linkage/viewmodel.js
styles.css

Update the scheme for Job Housing Linkage Fee for 2020
The job-linkage on the 2nd page, has changed.
Basically, the options and the fees will change depending on the office space whether it >= 50k or not. and there is a lab space or not.
New radio buttons for the choices were added and ready function is rewritten to check the form is ready or not. (e.g. if office space > 0, the radio button should be checked)

261 job housing linkage 2020

---

fees/citywide-childcare-residential/settings.json

update minor changes - child care

Update child care fee - residential

---

fees/van-ness-market-community-facility/component.js
fees/van-ness-market-community-facility/readme.md
fees/van-ness-market-community-facility/settings.json
fees/van-ness-market-community-facility/template.html
fees/van-ness-market-community-facility/viewmodel.js
settings.json

Add a new fee for 2021, #268
Van Ness & Market Community Facility Fee

Add van ness market community facility fee, #268

---

fees/affordable-housing/settings.json

Inclusionary Affordable Housing Program Fee update - affordable housing fee increased to 217.84.

Update to Inclusionary Affordable Housing fee

---

fees/affordable-housing/settings.json
fees/balboa-park-infrastructure/settings.json
fees/bicycle-parking-in-lieu/settings.json
fees/central-soma-community-facilities/settings.json
fees/central-soma-infrastructure/settings.json
fees/citywide-childcare-hotel-office/settings.json
fees/citywide-childcare-residential/settings.json
fees/downtown-park-fee/settings.json
fees/downtown-special-development-district-open-space/settings.json
fees/eastern-neighborhoods-infrastructure/settings.json
fees/eastern-neighborhoods-non-residential-open-space/settings.json
fees/eastern-neighborhoods-residential-open-space/settings.json
fees/jobs-housing-linkage/settings.json
fees/market-octavia-affordable-housing/settings.json
fees/market-octavia-infrastructure/settings.json
fees/north-of-market-residential-special-use-district-affordable-housing-fee/settings.json
fees/public-art/settings.json
fees/rincon-hill-infrastructure/settings.json
fees/soma-community-stabilization-fee/settings.json
fees/transit-center-open-space/settings.json
fees/transit-center-transportation/settings.json
fees/transportation-sustainability-fee/settings.json
fees/union-square-park-recreation-and-open-space/settings.json
fees/van-ness-market-community-facility/settings.json
fees/van-ness-market-infrastructure/settings.json
fees/visitacion-valley-infrastructure/settings.json
settings.json

269_New_Planning_Code_URLs - updated base URL and URL suffixes for all fees, due to migration to new Planning Code website.

Updated URLs to new Planning Code website

---

fees/eastern-neighborhoods-non-residential-open-space/readme.md
fees/eastern-neighborhoods-non-residential-open-space/settings.json
fees/eastern-neighborhoods-non-residential-open-space/template.html
fees/eastern-neighborhoods-non-residential-open-space/viewmodel.js
fees/eastern-neighborhoods-residential-open-space/readme.md
fees/eastern-neighborhoods-residential-open-space/settings.json
fees/eastern-neighborhoods-residential-open-space/template.html
fees/eastern-neighborhoods-residential-open-space/viewmodel.js
fees/transportation-sustainability-fee/settings.json
fees/transportation-sustainability-fee/template.html
fees/transportation-sustainability-fee/viewmodel.js

Transportation Sustainability Fee and Open Space Fee are updated for Central SoMa SUA, #276

Central soma fee update

---

fees/balboa-park-infrastructure/template.html
fees/balboa-park-infrastructure/viewmodel.js
fees/central-soma-community-facilities/template.html
fees/central-soma-community-facilities/viewmodel.js
fees/central-soma-infrastructure/template.html
fees/central-soma-infrastructure/viewmodel.js
fees/eastern-neighborhoods-infrastructure/template.html
fees/market-octavia-affordable-housing/template.html
fees/market-octavia-affordable-housing/viewmodel.js
fees/market-octavia-infrastructure/template.html
fees/market-octavia-infrastructure/viewmodel.js
fees/rincon-hill-infrastructure/template.html
fees/rincon-hill-infrastructure/viewmodel.js
fees/van-ness-market-infrastructure/template.html
fees/visitacion-valley-infrastructure/template.html
fees/visitacion-valley-infrastructure/viewmodel.js

Logic fixes for several impact fees. Discount nonResToRes and pdrToRes landuse from total resNew before calculating fee.

279 impact fees methods 2024
